FROM golang:alpine

LABEL org.opencontainers.image.source=https://github.com/s3rj1k/docker-images
LABEL org.opencontainers.image.licenses=BSD-3-Clause

RUN apk --no-cache add \
    bash \
    gcc \
    mc \
    musl-dev \
    nano
